# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('pubkey', models.TextField()),
                ('canal', models.CharField(max_length=20, unique=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='msg', max_length=3)),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField(editable=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixa_de_entrada', to='api.Identidade')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixa_de_saida', to='api.Identidade')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
    ]
