# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadeCompartilhada',
            fields=[
                ('identidade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Identidade')),
                ('privkey', models.TextField()),
            ],
            bases=('api.identidade',),
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ('-data',)},
        ),
    ]
