# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 14:05
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidade',
            name='compromised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identidade',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='identidade',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
