# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160728_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='validade',
            field=models.DateTimeField(editable=False),
        ),
    ]
