# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160502_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identidadecompartilhada',
            name='identidade_ptr',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('msg', 'Mensagem'), ('grp', 'Convite')], default='msg', max_length=3),
        ),
        migrations.DeleteModel(
            name='IdentidadeCompartilhada',
        ),
    ]
