# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170919_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identidade',
            name='description',
            field=models.TextField(),
        ),
    ]
