# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170919_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identidade',
            name='canal',
        ),
    ]
