# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_identidade_canal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatarios',
            field=models.ManyToManyField(related_name='caixa_de_entrada', to='api.Identidade'),
        ),
    ]
