# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170920_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='tipo',
        ),
        migrations.AddField(
            model_name='identidade',
            name='shared',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
